export { Payment } from "./Payment";
export { Articles } from "./Articles";
export { Settings } from "./Settings";
export { MyArticles } from "./MyArticles";
export { BankSettings } from "./BankSettings";
export { ChangePassword } from "./ChangePassword";
export { EvaluationResult } from "./EvaluationResult";
export { PersonalSettings } from "./PersonalSettings";
export { SingleArticleView } from "./SingleArticleView";
